env:
  id: ALE/SpaceInvaders-v5
  seed: 0
  frame_stack: 4

training:
  total_steps: 100000
  eval_every: 10000
  log_every: 1000
  device: cuda

ddqn:
  #architecture
  n_channels: 4
  gamma: 0.99
  double_dqn: true
  target_update: 100000
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 100000
  #training
  l_start: 50000
  total_steps: 1000000
  lr: 0.0001
  train_f: 4
  batch_size: 32
  buffer_size: 100000
  n_checkpoints: 0 #5
  log_every: 5000
  save_dir: runs/ddqn
  checkpoints_dir: checkpoints/ddqn
  #evaluation
  path_best_model: runs/ddqn/2026_01_31/ddqn_1000000.pt

ppo:
  #architecture
  gamma: 0.99
  lr: 0.0003
  clip_eps: 0.2
  gae_lambda: 0.95
  rollout_steps: 2048
  update_epochs: 4
  batch_size: 64
  seed: 0
  #training
  log_every: 50
  total_steps: 1000
  n_checkpoints: 0 #5
  save_dir: runs/ppo
  checkpoints_dir: checkpoints/ppo
  #evaluation
  path_best_model: runs/ppo/2026_02_01/ppo_1000.pt

sac:
  #architecture
  gamma: 0.99
  alpha: 0.2
  batch_size: 32
  replay_size: 500000
  tau: 0.005
  updates_per_step: 1
  max_grad_norm: 10.0
  #training
  log_every: 1000
  start_steps: 20000
  total_steps: 100000
  save_dir: runs/sac
  checkpoints_dir: checkpoints/sac
  actor_lr:  0.0003
  critic_lr: 0.0003
  eval_every: 10000000000000000000  #per i checkpoints 
  #evaluation
  path_best_model: runs/sac/2026_02_01/sac_100000.pt

sarfa:
  outdir: ./outputs
  seed: 123
  stride: 4
  patch: 8
  ddqn:
    fill_mode: "mean"
    batch_size: 64
    use_advantage: true
    clamp_positive: true
    use_action_flip: true
    flip_weight: 2.0
  ppo:
    in_channels: 4
    fill_mode: "mean"
    batch_size: 64
  sac:
    in_channels: 4
    fill_mode: "mean"
    batch_size: 64
    clamp_positive: true
    use_action_flip: true
    flip_weight: 2.0
    occlude_only_last_frame: true


eval:
  seed: 42
  n_episodes: 10
  n_episodes_render: 3
 
