env:
  id: ALE/SpaceInvaders-v5
  seed: 0
  frame_stack: 4

training:
  total_steps: 1000000
  eval_every: 100000
  log_every: 10000
  device: cuda

ddqn:
  n_channels: 4
  gamma: 0.99
  lr: 0.00001
  train_f: 4
  l_start: 50000
  double_dqn: true
  batch_size: 32
  buffer_size: 100000
  target_update: 10000
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 1000000
  n_checkpoints: 5
  log_every: 1000
  total_steps: 1000000
  save_dir: runs/ddqn
  checkpoints_dir: checkpoints/ddqn
  path_best_model: runs/ddqn/2026_01_25/ddqn_1000000.pt

ppo:
  gamma: 0.99
  lr: 0.0003
  clip_eps: 0.2
  gae_lambda: 0.95
  rollout_steps: 128
  epochs: 4
  batch_size: 64
  seed: 0
  eval_every: 100
  log_every: 1000
  total_steps: 10000
  n_checkpoints: 5
  save_dir: runs/ppo
  checkpoints_dir: checkpoints/ppo
  path_best_model: runs/ppo/2026_01_25/ppo_1000000.pt

sac:
  gamma: 0.99
  alpha: 0.2
  actor_lr:  0.0003
  critic_lr: 0.0003
  batch_size: 128
  replay_size: 200000
  start_steps: 200
  tau: 0.005
  updates_per_step: 1
  log_every: 1000
  total_steps: 10000
  eval_every: 1000
  max_grad_norm: 10.0
  save_dir: runs/sac
  checkpoints_dir: checkpoints/sac
  path_best_model: runs/sac/2026_01_27/sac_10000.pt

sarfa:
  outdir: ./outputs
  seed: 123
  stride: 4
  patch: 8
  ddqn:
    fill_mode: "mean"
    batch_size: 64
    use_advantage: true
    clamp_positive: true
    use_action_flip: true
    flip_weight: 2.0
  ppo:
    in_channels: 4
    fill_mode: "mean"
    batch_size: 64
  sac:
    in_channels: 4
    fill_mode: "mean"
    batch_size: 64
    clamp_positive: true
    use_action_flip: true
    flip_weight: 2.0
    occlude_only_last_frame: true


eval:
  seed: 42
  n_episodes: 10
  n_episodes_render: 1
 
